default: &default
  adapter: postgresql
  encoding: unicode
  username: <%= ENV['PG_USERNAME'] %>
  password: <%= ENV['PG_PASSWORD'] %>
  pool: 8

development:
  <<: *default
  host: localhost
  database: baker_wonder

test:
  <<: *default
  database: baker_test<%= ENV['TEST_ENV_NUMBER'] %>

production:
  <<: *default
  database: baker_production
